twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  welcome-message: Welcome to Twitter to Kafka Service

  # Mock tweets
  enable-mock-tweets: false
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-ms-sleep: 10000 # tweets sleep interval before next iteration

  # author_id will give the user ID
  twitter-v2-base-url: https://api.twitter.com/2/tweets/search/stream?tweet.fields=created_at&expansions=author_id
  enable-v2-tweets: true
  enable-v1-tweets: false
  twitter-v2-rules-base-url:  https://api.twitter.com/2/tweets/search/stream/rules
#  twitter-v2-bearer-token: # make sure to add this ti local variables: export  TWITTER_BEARER_TOKEN=<twitter token>

# Retry configuration
retry-config:
  initial-interval-ms : 1000
  max-interval-ms: 10000
  multiplier: 2.0
  max-attempts: 3
  sleep-time-ms: 2000

# Kafka configuration
kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092 # kafka broker listeners defined in kafka_cluster.yml
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-topic
  number-of-partitions: 3
  replication-factor: 3