twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  welcome-message: Welcome to Twitter to Kafka Service

  # Mock tweets
  enable-mock-tweets: false
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-ms-sleep: 10000 # tweets sleep interval before next iteration

  # author_id will give the user ID
  twitter-v2-base-url: https://api.twitter.com/2/tweets/search/stream?tweet.fields=created_at&expansions=author_id
  enable-v2-tweets: true
  enable-v1-tweets: false
  twitter-v2-rules-base-url:  https://api.twitter.com/2/tweets/search/stream/rules
#  twitter-v2-bearer-token: # make sure to add this ti local variables: export  TWITTER_BEARER_TOKEN=<twitter token>

# Retry configuration
retry-config:
  initial-interval-ms : 1000
  max-interval-ms: 10000
  multiplier: 2.0
  max-attempts: 3
  sleep-time-ms: 2000

# Kafka configuration
kafka-config:
  # kafka broker listeners defined in kafka_cluster.yml
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-topic
  number-of-partitions: 3
  replication-factor: 3

# Kafka producer configuration
kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.LongSerializer # using the Long variable type for key
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer # KafkaAvroSerializer is a confluent library
  compression-type: snappy # using snappy for compression (can use others such as gzip & etc). Compression will also increase the throughput
  acks: all # waiting for acknowledgement from all replicas (if set to 1 broker-1 will be updated and teh respond back, if set 0, respond back immediately)
  batch-size: 16384
  batch-size-boost-factor: 100 # increase this value to enable higher throughput
  linger-ms: 5 # delay added to collect data and then convert to batches
  request-timeout-ms: 60000 # 60 seconds
  retry-count: 5 # retry 5 times in case of an error